name: Deploy Static Website to EC2

on:
  push:
    branches:
      - main  # Trigger deployment when there are changes on the 'main' branch

jobs:
  asad:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up the SSH private key to connect to EC2
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | tr -d '\r' > github_key.pem
          chmod 400 github_key.pem

      # Step 3: Copy the files to the EC2 instance
      - name: Copy Files to EC2 using SCP
        run: |
          scp -o StrictHostKeyChecking=no -i github_key.pem -P ${{ secrets.SSH_PORT }} -r ./ * ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/

      # Step 4: Restart Nginx on EC2 to serve the updated app
      - name: Restart Nginx on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i github_key.pem -p ${{ secrets.SSH_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo systemctl restart nginx
          EOF
